import './globals.css';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import TanstackReactQuery from '@/libs/providers/tanstack-react-query';
import { cn } from '@/libs/shared/utilities/cn';
import { ThemeProvider } from '@/libs/providers/theme-provider';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackReactQuery>{children}</TanstackReactQuery>
        </ThemeProvider>
      </body>
    </html>
  );
}
